app_blog/urls.py
from django.urls import path
from .import views


app_name = 'app_blog'


urlpatterns = [
    path('', views.blog_list, name="blog_list")
]

app_login/urls.py
from django.urls import path
from app_login import views

app_name = 'app_login'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.home, name="home")
]

app_blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Enter Title")
    slug = models.SlugField(max_length=300, unique=True)
    blog_content = models.TextField(verbose_name="Enter your post")
    blog_image = models.ImageField(upload_to='blog_image', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


    def __str__ (self):
        return self.blog_title
    

class Comment (models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_user')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')

app_login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pic')

app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User



class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

app_blog/views.py
from django.shortcuts import render

# Create your views here.

def blog_list(request):
    return render(request, 'app_blog/blog_list.html')

app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from app_login.forms import SignUpForm, UserProfileChange

# Create your views here.

def signup(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    
    diction = {'form': form, 'registered':registered}

    return render(request, 'app_login/signup.html', context=diction)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
    return render (request, 'app_login/login.html', context={'form':form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


@login_required
def profile(request):
    return render(request, 'app_login/profile.html', context={})


@login_required
def user_change(request):
    current_user = request.user
    changed = False
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
            changed = True
    return render (request, 'app_login/change_profile.html', context={'form':form, 'changed':changed})

blog/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect


def home(request):
    return HttpResponseRedirect(reverse('app_blog:blog_list'))

templates/app_blog/blog_list.html
{% extends 'base.html' %}


{% block body %}

<h1>This is blog page</h1>
{% endblock %}

templates/app_login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %}
{% block body %}

{% if changed %}

    <div class="alert alert-sucess">
        Profile Updated Sucessfully! <a href="{% url 'app_login:profile' %}">Let's Go Back</a>
    </div>

{% endif %}


<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-warning btn-sm"> Change</button>
</form>







{% endblock %}

templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block block_title %} Login {% endblock %}
{% block body %}

<h2>Login:</h2>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>


{% endblock %}

templates/app_login/profile.html
{% extends 'base.html' %}
{% block block_title %} Profile {% endblock %}
{% block body %}

<h2>Your Profile</h2>
<br>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name:  {{ user.first_name }} {{ user.last_name }}</p>

<a href="{% url 'app_login:user_change' %}" class="btn btn-warning btn-sm">Change Profile</a>

{% endblock %}

templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}
{% block body %}
{% if registered %}
<div class="alert alert-sucess">
    Account created Successfully! <a href="{% url 'app_login:login' %}">Login Here</a>
</div>
{% else %}
<h2>Create New Account</h2>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">Create New Account</button>
</form>
<br>
<p>Already have an Account? <a href="{% url 'app_login:login' %}">Login Here</a></p>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block block_title %} Blog {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'app_login:profile' %}" class="nav-link">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'app_login:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'app_login:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'app_login:signup' %}">Signup</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>


      <div class="container">
        {% block body %}
        {% endblock %}
      </div>








    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>